Refinement/remove bootstrap reboot
pressden/emma pull request #149
Opened 2021-03-17 18:32 UTC by eric-michel

2021-03-23 14:00 UTC, dswebsme requested changes

2021-03-25 00:09 UTC, eric-michel commented on src/sass/common/_reset.scss
> +}
Looks like a lot of stuff was missing here. For some reason, the User Agent stylesheet gave a completely different font family to inputs!
```
input,
button,
select,
optgroup,
textarea {
  margin: 0;
  font-family: inherit;
  @include font-size(inherit);
  line-height: inherit;
}
```

2021-03-25 00:10 UTC, eric-michel commented on src/sass/common/_reset.scss
> +
Yep, you were exactly right after some testing. Apparently, with the default `vertical-align`, a bit of space is added between the bottom of the image and its container. Weird bug. I've added this back in and it resolved the problem.

2021-03-25 00:12 UTC, eric-michel commented
@dswebsme if you have a few minutes tomorrow, pull this down and let me know if you see any other issues. I've pretty thoroughly tested the bugs you mentioned, but I'd rather you give it another look just to be safe!

2021-03-25 14:24 UTC, dswebsme approved these changes

2021-03-25 14:24 UTC, merged